name: Build with Nuitka (Standalone)

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt nuitka ordered-set zstandard

      - name: Build ytdl-noff
        run: |
          python -m nuitka --standalone --remove-output --windows-console-mode=disable --enable-plugin=pylint-warnings --output-dir=dist ytdl-noff.py

      - name: Build ytdl-ff
        run: |
          python -m nuitka --standalone --remove-output --windows-console-mode=disable --enable-plugin=pylint-warnings --output-dir=dist --include-data-file="dependencies\\ffmpeg.exe=dependencies\\ffmpeg.exe" ytdl-ff.py

      - name: Package builds
        run: |
          cd dist
          Compress-Archive -Path "ytdl-noff" -DestinationPath "ytdl-noff.zip"
          Compress-Archive -Path "ytdl-ff" -DestinationPath "ytdl-ff.zip"
          cd ..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ytdl-builds
          path: dist/*.zip
