name: Build YoutubeDownloader

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka pytubefix beautifulsoup4 requests pywin32
      - name: Build YoutubeDownloader (without FFmpeg)

        run: python -m nuitka --standalone --remove-output --windows-console-mode=disable --output-dir=dist --assume-yes-for-downloads --enable-plugin=tk-inter ytdl-noff.py

      - name: Build YoutubeDownloader (with FFmpeg)
        run: python -m nuitka --standalone --remove-output --windows-console-mode=disable --output-dir=dist --assume-yes-for-downloads --enable-plugin=tk-inter --include-data-file="dependencies\\ffmpeg.exe=dependencies\\ffmpeg.exe" ytdl-ff.py

      - name: Zip both builds
        run: |
          cd dist
          powershell Compress-Archive -Path ytdl-noff.dist -DestinationPath ytdl-noff.zip
          powershell Compress-Archive -Path ytdl-ff.dist -DestinationPath ytdl-ff.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: YoutubeDownloader-Builds
          path: dist/*.zip
