name: Build YoutubeDownloader

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pytubefix pywin32

      - name: Build YoutubeDownloader (without FFmpeg)
        run: pyinstaller --onedir --noconfirm --name "ytdl-noff" --noconsole ytdl-noff.py

      - name: Build YoutubeDownloader (with FFmpeg)
        run: pyinstaller --onedir --noconfirm --name "ytdl-ff" --noconsole --add-data "dependencies;dependencies" ytdl-ff.py

      - name: Zip both builds
        run: |
          cd dist
          powershell Compress-Archive -Path ytdl-noff -DestinationPath ytdl-noff.zip
          powershell Compress-Archive -Path ytdl-ff -DestinationPath ytdl-ff.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: YoutubeDownloader-Builds
          path: dist/*.zip